export const MarketStatus = {
    Rejected: 'Rejected',
    Pending: 'Pending',
    Approved: 'Approved',
    Resolved: 'Resolved',
};
  
export const TradingStatus = {
    Pause: 'Pause',
    Open: 'Open',
    Close: 'Close',
};
  
export const WinningOutcome = {
    Yes: 'Yes',
    No: 'No',
};
  
export const TokenType = {
    YES: 'YES',
    NO: 'NO',
};
  

export const markets= [
    {
        market_key: "market_1",
        market_id: "1",
        market_public_key: "pubkey_perplexity_1",
        creator: "Creator 1",
        pollQuestion: "Will Perplexity get acquired before the end of April 2025 ?",
        image_url: "/perplexity.png",
        video_url: "/perplexity.mp4",
        volume: 1.2,
        comments: 12,
        yes_price: 0.6,
        no_price: 0.4,
        categories: ["Tech", "Business", "New"],
        tokens: ["YES_TOKEN_1", "NO_TOKEN_1"],
        tradingStatus: TradingStatus.Open,
        status: MarketStatus.Approved
    },
    {
        market_key: "market_2",
        market_id: "2",
        market_public_key: "pubkey_nikhil_2",
        creator: "Creator 11",
        pollQuestion: "Will Nikhil Kamath/Zerodha buy stake in United Breweries before the end of March 2025 ?",
        image_url: "/nikhil.png",
        video_url: "/nikhilkamath.mp4",
        volume: 4.2,
        comments: 18,
        yes_price: 0.5,
        no_price: 0.5,
        categories: ["Business", "Finance", "New","Politics"],
        tokens: ["YES_TOKEN_2", "NO_TOKEN_2"],
        tradingStatus: TradingStatus.Open,
        status: MarketStatus.Approved
    },
    {
        market_key: "market_3",
        market_id: "3",
        market_public_key: "pubkey_madrid_3",
        creator: "Creator 2",
        pollQuestion: "Will Real Madrid score atleast 2 goals against RCD Mallorca in their next match ?",
        image_url: "/realmadrid.png",
        video_url: "/RealMadrid.mp4",
        volume: 0.7,
        comments: 15,
        yes_price: 0.7,
        no_price: 0.3,
        categories: ["Sports", "Football", "Trending","Politics"],
        tokens: ["YES_TOKEN_3", "NO_TOKEN_3"],
        tradingStatus: TradingStatus.Open,
        status: MarketStatus.Approved
    },
    {
        market_key: "market_4",
        market_id: "4",
        market_public_key: "pubkey_novak_4",
        creator: "Creator 6",
        pollQuestion: "Will Novak Djokovic win the Australian Open Men's Singles title 2025?",
        image_url: "/novak.png",
        video_url: "/novak.mp4",
        volume: 0.9,
        comments: 11,
        yes_price: 0.46,
        no_price: 0.54,
        categories: ["Sports", "Tennis"],
        tokens: ["YES_TOKEN_4", "NO_TOKEN_4","Politics"],
        tradingStatus: TradingStatus.Open,
        status: MarketStatus.Approved
    },
    {
        market_key: "market_5",
        market_id: "5",
        market_public_key: "pubkey_marvels_5",
        creator: "Creator 4",
        pollQuestion: "Will 'The Marvels' surpass $200 million in its opening weekend by January 25, 2025?",
        image_url: "/themarvels.png",
        video_url: "/themarvels.mp4",
        volume: 2.4,
        comments: 17,
        yes_price: 0.8,
        no_price: 0.2,
        categories: ["Entertainment", "Movies"],
        tokens: ["YES_TOKEN_5", "NO_TOKEN_5"],
        tradingStatus: TradingStatus.Open,
        status: MarketStatus.Approved
    },
    {
        market_key: "market_6",
        market_id: "6",
        market_public_key: "pubkey_zepto_6",
        creator: "Creator 2",
        pollQuestion: "Will Zepto announce another round of funding before the end of January 2025?",
        image_url: "/zepto.png",
        video_url: "/zepto.mp4",
        volume: 1.1,
        comments: 10,
        yes_price: 0.32,
        no_price: 0.68,
        categories: ["Tech", "Business"],
        tokens: ["YES_TOKEN_6", "NO_TOKEN_6"],
        tradingStatus: TradingStatus.Open,
        status: MarketStatus.Approved
    },
    {
        market_key: "market_7",
        market_id: "7",
        market_public_key: "pubkey_nvidia_7",
        creator: "Creator 1",
        pollQuestion: "Will Nvidia's market cap hit $4 Trillion by the end of March ?",
        image_url: "/nvidia.png",
        video_url: "/nvidia_5T_mcap.mp4",
        volume: 1.3,
        comments: 20,
        yes_price: 0.45,
        no_price: 0.55,
        categories: ["Tech", "Business", "Finance", "New", "Trending"],
        tokens: ["YES_TOKEN_7", "NO_TOKEN_7"],
        tradingStatus: TradingStatus.Open,
        status: MarketStatus.Approved
    },
    {
        market_key: "market_8",
        market_id: "8",
        market_public_key: "pubkey_conor_8",
        creator: "Creator 9",
        pollQuestion: "Will Conor McGregor retire in 2025?",
        image_url: "/conor.png",
        video_url: "/conor.mp4",
        volume: 9,
        comments: 22,
        yes_price: 0.7,
        no_price: 0.3,
        categories: ["Sports", "MMA", "Trending"],
        tokens: ["YES_TOKEN_8", "NO_TOKEN_8"],
        tradingStatus: TradingStatus.Open,
        status: MarketStatus.Approved
    },
    {
        market_key: "market_9",
        market_id: "9",
        market_public_key: "pubkey_gukesh_9",
        creator: "Creator 10",
        pollQuestion: "Will an Indian player win the FIDE Grand Prix series event scheduled before February 22, 2025?",
        image_url: "/gukesh.png",
        video_url: "/gukesh.mp4",
        volume: 0.6,
        comments: 23,
        yes_price: 0.8,
        no_price: 0.2,
        categories: ["Sports", "Chess"],
        tokens: ["YES_TOKEN_9", "NO_TOKEN_9"],
        tradingStatus: TradingStatus.Open,
        status: MarketStatus.Approved
    }
];